### ISSUE TITLE
Does not generate index.html when there are failing test cases and `includeFailureMsg` = true

### ISSUE THREAD

**Issue by chefhoobajoob** [Hargne/jest-html-reporter#1]
With the configuration below, this project only generates build/reports/jest/index.html when all the tests pass. When any tests fail, no report is generated. Jest version is 18.1.0.
```
  "jest": {
    "verbose": true,
    "testResultsProcessor": "./node_modules/jest-html-reporter"
  },
  "jest-html-reporter": {
    "pageTitle": "Jest Tests",
    "outputPath": "build/reports/jest/index.html",
    "includeFailureMsg": true
  },
```

**Comment by chefhoobajoob** [comment]
If 'includeFailureMsg' is false, a report is generated (but, of course, there are no failure messages)

**Comment by chefhoobajoob** [comment]
This may have to do with the content of the error message. I noticed in some failures the jest message has text that includes angle brackets. May need to replace these with &lt/&gt or something.

**Comment by chefhoobajoob** [comment]
With this error message from jest:

```
Error: expect(received).toEqual(expected)

Expected value to equal:
  204

[...rest of error message ]
```

...the following line:
```
failureMsgDiv.ele('p', { class: 'failureMsg' }, failureMsg);
```

...generates this error:
```
Error: Invalid character () in string: [jest error message above] at index 7
```

...this is probably because jest is including some control or other special characters that are not legal xml, and they haven't been escaped. See: https://github.com/oozcitak/xmlbuilder-js/issues/147

**Comment by Hargne** [comment]
Thanks for reporting this. I will try to fix the issue as soon as possible!
