### ISSUE TITLE
Test reports are not showing after generating index.html file

### ISSUE THREAD

**Issue by akash-int** [Hargne/jest-html-reporter#101]
This is my package.json & I have modified **"test": "set CI=true &&react-scripts test --env=jsdom --testResultsProcessor=./node_modules/jest-html-reporter",** this line in scripts object of the package.json file
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.19.2",
    "bootstrap": "^4.4.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "jest-html-reporter": "^3.1.0",
    "node-sass": "^4.13.1",
    "react": "^16.13.1",
    "react-bootstrap": "^1.0.0",
    "react-dom": "^16.13.1",
    "react-flags-select": "^1.1.12",
    "react-loader-spinner": "^3.1.5",
    "react-reveal": "^1.2.2",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1",
    "react-svg": "^11.0.15",
    "react-test-renderer": "^16.13.1",
    "react-toastify": "^5.5.0",
    "rete": "^1.4.3-rc.1",
    "rete-area-plugin": "^0.2.1",
    "rete-connection-plugin": "^0.9.0",
    "rete-context-menu-plugin": "^0.5.2",
    "rete-react-render-plugin": "^0.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "set CI=true &&react-scripts test --env=jsdom --testResultsProcessor=./node_modules/jest-html-reporter",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**This is my jesthtmlreporter.config.json**
{
	"pageTitle": "Test Report 3S Money",
	"outputPath": "ut-report/index.html",
	"includeFailureMsg": true
}

Any help will be appreciated. Thanks in advance!

**Comment by Hargne** [comment]
Hi,
When using create-react-app there are a few quirks when using Jest. In this case you would need to use the `reporters` option instead of `testResultsProcessor`, like so:

```
set CI=true &&react-scripts test --env=jsdom --reporters=default --reporters=./node_modules/jest-html-reporter
```

This should render a test report.

**Comment by akash-int** [comment]
Hi @Hargne 
Thanks for your quick response. Now it's working perfectly.

Thanks a lot! :-)
