### ISSUE TITLE
Group tests in suites

### ISSUE THREAD

**Issue by senner008** [Hargne/jest-html-reporter#102]
Would be nice to have

**Comment by Hargne** [comment]
Hi,
In what way do you mean by grouping tests in suites? And grouping by what?

**Comment by senner008** [comment]
I mean group by test 'describe' instead of group by file in the html. Right now I see each test grouped by file and then by test 'it'

**Comment by Hargne** [comment]
Alright, yes that would probably be possible to do.

(Although, it would group tests from files across your project, which IMO would be counterintuitive. A test file is meant to represent the test of the file/method you're testing. And if you have additional tests testing the same method in a completely different part of the project it is perhaps time to consider restructuring. It is also worth mentioning that the grouping per file, is as per Jest's response)

**Comment by Hargne** [comment]
I will close this as per the comment above
