### ISSUE TITLE
Show relative path to test files

### ISSUE THREAD

**Issue by senner008** [Hargne/jest-html-reporter#103]
Instead of the absolute path
Is it possible?

**Comment by Hargne** [comment]
The path string to each test is what we receive from Jest. If you wanted to get the relative path, it would most likely have to be a manual change of the string.

**Comment by Hargne** [comment]
I'm going to close this as I don't see the value of manipulating the response from Jest in this case.
This said though, feel free to open a PR if you still feel that this would be valuable to have.
