### ISSUE TITLE
Need to append date and time to the filename?

### ISSUE THREAD

**Issue by senthkum** [Hargne/jest-html-reporter#112]
Hi Team,

I would like to add the date and time to the filename, I have used the below code in package.json and it did not work. Could you please help with the code, for every iteration I would require to create a new file. Not sure how I can use the escaping in the filename.
eg:  sample-execution-report-20200914132407.html

    "reporters": [
      "default",
      [
        "jest-html-reporters",
        {
          "publicPath": "./html-report",
          "filename": "sample-execution-report-\"dateFormat(now)\".html",
          "pageTitle": "API execution result",
          "expand": true
        }
      ]
    ] 
and even tried "filename": "sample-execution-report-\"+$(date \"+ %Y-%m-%d-%H-%M-%S \"+).html",
and many other also, but for all it through the same error.
Error: ENOENT: no such file or directory, open 'D:\OB-Automation\html-report\sample-execution-report-"dateFormat(now)".html'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at MyCustomReporter.onRunComplete

**Comment by Hargne** [comment]
Hi,

If you configure jest using a `jest.config.js`-file, you are able to do the following:

```
var now = new Date();
module.exports = {

  ...rest of your your config

  reporters: [
    "default",
    [
      "jest-html-reporter",
      {
        publicPath: "./html-report",
        filename: `<rootDir>/sample-execution-report-${now.toISOString()}.html`,
        pageTitle: "API execution result",
        expand: true
      }
    ]
  ]
};
```

**Comment by Hargne** [comment]
I am closing this issue for now. Feel free to open it again if you feel that the answer was invalid.
