### ISSUE TITLE
keep the colorized display of differences

### ISSUE THREAD

**Issue by scim-dim-technique** [Hargne/jest-html-reporter#115]
On the command line the differences appear as colorized revision marks. In the html report these marks are absent. It is not a simple question of css: there are no html tags which materialize these differences.
Can you provide an option to keep these marks in the html.

**Comment by Hargne** [comment]
Hi, 
I am a bit unsure of what diffs you are referring to. 
Is it possible to get a more detailed description of what it is you are after?

**Comment by Hargne** [comment]
I'm closing this due to lack of response. Feel free to open with a response if it is still relevant.
