### ISSUE TITLE
jest-html-reporter >> TypeError: Cannot read property 'unchecked' of undefined

### ISSUE THREAD

**Issue by darkship** [Hargne/jest-html-reporter#120]
Hi,
I would like to use the html reporter but I got the followig error and the report is empty
```
jest-html-reporter >> TypeError: Cannot read property 'unchecked' of undefined
jest-html-reporter >> Report generated (/home/ashra/enscape/webshop/e2e/test-report.html)
```

I'm using `testResultsProcessor: './node_modules/jest-html-reporter',` in my jest config with jesthtmlreporter.config.json `{}`

package.json
```
  "dependencies": {
    "@types/expect-puppeteer": "^4.4.5",
    "@types/jest-environment-puppeteer": "^4.4.1",
    "@types/puppeteer": "^5.4.3",
    "dotenv": "^9.0.1",
    "faker": "^5.5.3",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3",
    "jest-html-reporter": "^3.3.0",
    "jest-puppeteer": "^5.0.3",
    "puppeteer": "^9.1.1",
    "ts-jest": "^26.5.6",
    "typescript": "^4.2.4"
  }
```

**Comment by sohan** [comment]
Just ran into this too! It seems like this line the culprit: https://github.com/Hargne/jest-html-reporter/blob/master/src/index.ts#L45. On jest 26 with jest-circus at least, that line should read:

```
if (Object.prototype.hasOwnProperty.call(globalConfig, "testResults")) {
-  setupAndRun(globalConfig.testResults, options, globalConfig);
+  setupAndRun(globalConfig, options, globalConfig);
```

I worked around this with a customer test processor that wraps results in an object:

```
const JestHtmlReporter = require('jest-html-reporter').default;
module.exports = function TestResultsProcessor(results) {
  return JestHtmlReporter({ testResults: results }, {});
}
```

**Comment by Hargne** [comment]
Hi, the Jest package in this project is based on Jest v25, which might be the reason behind this.
I will attempt an upgrade to see if it would resolve your issue

**Comment by Hargne** [comment]
Version `3.4.0-beta.0` is now available, it would be highly appreciated if you could help out testing if this release solves your issue.

#### Side notes:
I did some testing by setting up a local replica of the setup you mentioned and I could not reproduce the issue. 
The `testResultsProcessor` option has always been slightly unpredictable hence why the recommended approach is using Jests' `reporters`-option:

```
"reporters": [
	"default",
	["./node_modules/jest-html-reporter", {
		"pageTitle": "Test Report"
	}]
]
```

**Comment by darkship** [comment]
I don't have the error messages any more but it always renders the same report
![image](https://user-images.githubusercontent.com/3523710/117970973-9d5bc400-b329-11eb-87d3-ddb09cf3f85f.png)

**Comment by Hargne** [comment]
I put out `3.4.0-beta.1` where I believe I have solved the issue when running this plugin as a `testRestulsProcessor` instead of using the `reporters`-option.

Would you please verify before I release this? @darkship

**Comment by darkship** [comment]
Everything looks ok for me now
