### ISSUE TITLE
My console changes to green color (VSCode)

### ISSUE THREAD

**Issue by croraf** [Hargne/jest-html-reporter#13]
My console changes to green color when I use this reporter.
This is maybe a vscode issue.

**Comment by Hargne** [comment]
Does it change the entire console to green, or just the output of the report?

**Comment by croraf** [comment]
Entire console font color. So when I use console after that it types everything in green.

**Comment by Hargne** [comment]
I have not experienced this in VSCode personally nor in other terminals. This could potentially be an issue with the VSCode terminal and may not be related to the code itself.
If you have the time, please investigate if there are any similar reported issues with VSCode and what might have caused it!

**Comment by Hargne** [comment]
If anyone else experience this, please reopen this issue and I will do a proper investigation.

**Comment by Hargne** [comment]
This was fixed in [v0.5.5](https://github.com/Hargne/jest-html-reporter/commit/8b584fcc2821272a914e2a2f981be01ab9f43cdc)
