### ISSUE TITLE
Using deprecated options in the config stops a report from being generated 

### ISSUE THREAD

**Issue by d-thomson** [Hargne/jest-html-reporter#131]
Messed around for an hour or so wondering why I couldn't get a report to generate _only_ when I specified using darkTheme. Found PR #94 which deprecates and removes the theme option. Worth noting that bogus args are simply ignored, but using this option causes some failure for report generation. Any references to this should probably be removed from the docs and  codebase.

https://github.com/Hargne/jest-html-reporter/wiki/Test-Report-Themes

**Comment by Hargne** [comment]
Great finding!
I will try to update the docs asap
