### ISSUE TITLE
Doesn't support jest 28.

### ISSUE THREAD

**Issue by psoleckimoj** [Hargne/jest-html-reporter#146]
Jest is now at version 28, currently the `peerDependency` only supports jest 27 so it's stopping us updating.

**Comment by Hargne** [comment]
Hi,
Jest v28 was released 2 days ago and includes a bunch of breaking changes which also will affect this library.
In order for us to change the peerDependency, we also need to make sure that the library can handle v28

**Comment by psoleckimoj** [comment]
Thanks Johan, sorry no rush at all 🙂 👍

**Comment by jamesscott-tw** [comment]
Aside from upgrading to jest 28 (plus bumping anything else that needs bumping) and checking tests run is anything else required? If not, I'll open PR with upgraded libraries

**Comment by Hargne** [comment]
During a previous (brief) research, it seemed like the upgrade to v28 broke this library at a couple of places and would require some refactoring in order to work as intended.
But if you manage to upgrade, please do open a PR 👍
