### ISSUE TITLE
code coverage export

### ISSUE THREAD

**Issue by AvinashUtekar** [Hargne/jest-html-reporter#150]
can we export code coverage to html page?

**Comment by Hargne** [comment]
Yes, that is what this plugin does!
You can find the instructions on how to use it in the Readme.

**Comment by DankeF** [comment]
> Yes, that is what this plugin does! You can find the instructions on how to use it in the Readme.

Hello, you can specifically say how to set it to output the code coverage. I don't seem to find it, I'm sorry

**Comment by Hargne** [comment]
Sorry, I misread your question 🙃 
Collecting and displaying coverage is already an existing [built-in feature in Jest](https://jestjs.io/docs/cli#--coverageboolean) using Istanbul! Very neat tool 👍
