### ISSUE TITLE
Is there a way I can Display something other than file path here?

### ISSUE THREAD

**Issue by RobRukavina** [Hargne/jest-html-reporter#155]
![image](https://user-images.githubusercontent.com/65525430/220482273-5962089f-6403-4f35-8c93-0c4ddd73a192.png)

**Comment by Hargne** [comment]
Hi,
Not at the moment, no.
You can however inject a javascript using the `customScriptPath` param where you could target the class `suite-path` and modify each row.

**Comment by RobRukavina** [comment]
Thank you, that's what I was thinking of doing :)
