### ISSUE TITLE
jest 21 support?

### ISSUE THREAD

**Issue by morungos** [Hargne/jest-html-reporter#16]
Jest 21 is now out, and it all seems to work okay for me, but `package.json` is moaning because it isn't an allowed peer dependency. 

Can that be relaxed?

**Comment by Hargne** [comment]
Hi,
There was a pull request fixing this issue: https://github.com/Hargne/jest-html-reporter/pull/15
This was just merged and I will make sure to make an release on npm as well.

Thanks!

**Comment by morungos** [comment]
Excellent and many thanks (must have missed that in my search 😢)

**Comment by mrichmond** [comment]
@Hargne Can you bump the package version please?!

**Comment by Hargne** [comment]
Version **0.5.2** is now published on npm including this fix.
