### ISSUE TITLE
Added into report configuration additional flag "includeStackTrace": false

### ISSUE THREAD

**Issue by VadimNastoyashchy** [Hargne/jest-html-reporter#160]
Hello. I use the reporter for a very large number of tests and I would like to be able to remove the trace stack and live only a few rows with an error description, since in correctly described tests it is not necessary to have a trace and it is clear what the error is. This will save a very large amount of space on the reporter page while scrolling.

Suggestion is to add into report configuration additional flag "includeStackTrace": false (by default it should be true) if needs to hide stack trace from the report and just live only error mismatched message.

Now i use my custom script that opens and changes html file (removes only stack trace), but it will be great to can do it through the report config.

![example](https://user-images.githubusercontent.com/58398016/235094686-de20ed24-09d9-425e-b5f4-29a0e6a0da73.jpeg)

<img width="466" alt="Screenshot 2023-04-28 at 10 56 57" src="https://user-images.githubusercontent.com/58398016/235094727-50634407-fe0f-4163-b815-a3e1ccd3f54e.png">

**Comment by Hargne** [comment]
Hi @VadimNastoyashchy 
Thanks for the suggestion.

I created a PR (#161 ) if you could have a brief look if it suits your needs? If so, I will publish this ASAP.

**Comment by VadimNastoyashchy** [comment]
Thanks a lot)
