### ISSUE TITLE
reporter mode implemented not properly

### ISSUE THREAD

**Issue by joey-he8x** [Hargne/jest-html-reporter#34]
I tried 2.0.0 in reporter mode. It doesn't work out as expected.
jest --forceExit will exit before generated report.
I check the sourcecode, in CustomReporter#onRunComplete, actually jest expect the return is a promise and will await the promise before exit.

**Comment by Hargne** [comment]
Hi,

> I check the sourcecode, in CustomReporter#onRunComplete, actually jest expect the return is a promise and will await the promise before exit.

I don't know if I fully understand what you said there. Did you mean the report would be generated if `onRunComplete` would return a Promise?

As I've stated previously, I cannot personally reproduce this issue (it works as intended in my environments). If you have the solution, it would be highly appreciated if you sent in a Pull Request with the fix!

**Comment by Hargne** [comment]
This is being worked on in @ #35
