### ISSUE TITLE
Does not generate index.html/test report when there are failing test cases and `includeFailureMsg` = true

### ISSUE THREAD

**Issue by avne31** [Hargne/jest-html-reporter#40]

**Comment by avne31** [comment]
kindly help me in this.i'm stuck at that point

**Comment by avne31** [comment]
Hi Hargne,

I have not used jest-html-reporter in past. And I have not found any error related to jest-html-reporter. 
Html report is generated when all test cases are passed but did not get the report for failure case.
I am using jest to run frisby specs and jest-html-reporter for test result reporting. 

I have enabled the option 'includeFailureMsg: true' in package.json for failed cases.

package.json:

`    "name": "test",
    "jest": {
            "verbose": true,
            "testMatch": ["path"],
            "testResultsProcessor": "./node_modules/jest-html-reporter"
       },
        "jest-html-reporter": {
         "pageTitle": "Your test suite",
         "outputPath": "test-report.html",
         "includeFailureMsg": true
   },
    "dependencies": {
            "jest-html-reporter": "^2.3.0"
   }`

Thanks.

**Comment by Hargne** [comment]
Have you configured Jest to use jest-html-reporter?

Within jest.config.js:
```{
	"testResultsProcessor": "./node_modules/jest-html-reporter"
}```

**Comment by avne31** [comment]
I'm configuring jest in the package.json and didn't create the separate configuration file(jest.config.js).

the link I'm using:

https://www.npmjs.com/package/jest-html-reporter

**Comment by Hargne** [comment]
It's quite difficult to see the big picture of your project and why this would fail for you (I cannot reproduce the issue myself).

One thing you could attempt, is to replace the `testResultsProcessor` entry to the following:
```
"reporters": ["default", "./node_modules/jest-html-reporter"]
```

And then add the `"executionMode": "reporter"` within the jest-html-reporter configuration

**Comment by avne31** [comment]
thanks for your help Hargne.

now my problem is resolved, it shows that I want.

**Comment by Hargne** [comment]
Great to hear!
