### ISSUE TITLE
append all test results not to override

### ISSUE THREAD

**Issue by avne31** [Hargne/jest-html-reporter#41]
I want to append the test result not to override .

**Comment by Hargne** [comment]
Hi,

Appending to an existing file instead of writing out the latest test result would require a fundamental change to the entire plugin and perhaps even something I would suggest avoid doing in the first place because of the ever growing file size each time you run a test suite.

Out of curiosity though: what will the benefits be of storing all previous test results?

**Comment by avne31** [comment]
I'm running my script through the batch file and the same time I will pass variables because of my script demands.so jest invokes at all test and runs the file. that's why I want to append the test cases, it's not my curiosity it's my need here.

**Comment by avne31** [comment]
hi,

is there any way you can suggest because I'm stuck at that point from 3 days

thanks

**Comment by Hargne** [comment]
Please open this issue if you still feel that this is a necessary feature for this plugin.

**Comment by avne31** [comment]
I want to append all test result because of 2 things:
1. because some script calling multiple times through 1 cycle like(login account with primary user, login account with the secondary user and last but not the least login account as account owner ) here we can see the same script calling multiple times.

2. above one for 1 iteration, I want to run multiple iterations to test the script regressively.

**Comment by avne31** [comment]
and its request please reopen this issue because it may be need of others too.

**Comment by Hargne** [comment]
Please correct me if I didn't catch what you were going for - but from what I understand, you want to do the two following things:
- Test the same method multiple times with different parameters.
- Perform some kind of Regression Testing to ensure that changes in your code doesn't change the intended behaviour.

**Test the same method multiple times with different parameters.**
This is native to Jest (and similar testing frameworks). You can (and should) test a method in every possible way using Jest. You can find an example of this in this repository even - in [this file](https://github.com/Hargne/jest-html-reporter/blob/master/test/reportGenerator.spec.js). Here we test the `renderHtmlReport` method twice with different parameters. There are multiple tutorials on this to be found.

**Perform some kind of Regression Testing**
Regression Testing is beyond the scope of this plugin (whose purpose is not to test, but to report the outcome of Jest's test results in a report). However if you need to perform Regression Testing, I would advise to look at tools specifically built for that case. You can find a descriptive list over good tools [here](https://github.com/mojoaxel/awesome-regression-testing).

Lastly (as I've said previously), if this isn't what you're after - you could programmatically change the output directory/name of the test report on each run, which would essentially will give you the same result as to store everything in the same file.
