### ISSUE TITLE
How to show the coverage stat also?

### ISSUE THREAD

**Issue by adamchenwei** [Hargne/jest-html-reporter#42]
<img width="1146" alt="screen shot 2018-05-31 at 3 50 41 pm" src="https://user-images.githubusercontent.com/4201698/40805166-67b69d32-64eb-11e8-9463-36cd8adf1cd2.png">

I can see it in console, but I want to also see this part of the report in html reporter. how can I config it to show it?

Thanks!

**Comment by Hargne** [comment]
Hi,
What you're looking for is actually a part of the core Jest package called "coverage" and can render the test coverage results into html: https://facebook.github.io/jest/docs/en/configuration.html#collectcoverage-boolean
(see the coverageDirectory variable for how to output it)

**Comment by christopher-caldwell** [comment]
I think the issue was combining the 2 into one viewable file. The other reporters show coverage, this tool shows tests. Is there a way to combine them into one document?

**Comment by christopher-caldwell** [comment]
@Hargne bump
