### ISSUE TITLE
Configure output path from CLI

### ISSUE THREAD

**Issue by xilaraux** [Hargne/jest-html-reporter#46]
Hello.
Is there any way to configure `outputPath` from CLI? 
I mean something like that:
```
"scripts": {
        "jenkins:test": "npm run test --testResultsProcessor=jest-html-reporter --outputPath=../../reports"
},
```

**Comment by Hargne** [comment]
Hi,
Not at the moment unfortunately! And I have never seen the usage of the `--testResultsProcessor` when using Jest CLI - I cannot find it on their [documentation page](https://facebook.github.io/jest/docs/en/cli) either, which makes me think that this might not be possible at all.

**Comment by xilaraux** [comment]
Jest process it's CLI options as prior config, so all keys that can be in jest.config is legal CLI options.
![image](https://user-images.githubusercontent.com/17703730/41898232-1b43e15c-7932-11e8-93f8-b3f78443c9c4.png)

Also `jest-junit` describes this way in it's [documentation](https://github.com/jest-community/jest-junit#usage-as-testresultsprocessor).

**Comment by Hargne** [comment]
@xilaraux Regarding the issue above, the Readme is incorrect - it should be configured like this:
```
"reporters": [
	"default",
	["./node_modules/jest-html-reporter", {
		"pageTitle": "Test Report"
	}]
]
```
Thanks for pointing it out, I will update the Readme!
When it comes to the original question, I didn't know Jest CLI allowed for that. In that case (since it's configuring Jest and not this plugin), I suppose you should be able to enter the `reporters`-variable as a way to configure this plugin?

**Comment by xilaraux** [comment]
Can you provide an example, because I can't get how to configure plugin through `reporters`?

**Comment by Hargne** [comment]
When using the jest.config-file you would configure the plugin in the object following "jest-html-reporter" as such:

```
"reporters": [
	"default",
	["./node_modules/jest-html-reporter", {
		"pageTitle": "Test Suite Report",
		"outputPath": "test-report.html",
		"includeFailureMsg": true,
		"includeConsoleLog": true,
		"sort": "titleAsc"
	}]
]
´´´

**Comment by xilaraux** [comment]
Oh, yeah. Now I get it. I just thought that there is some way to configure plugin through CLI. 
Thank you for your help. 😄
