### ISSUE TITLE
how can i dynamically change outputPath

### ISSUE THREAD

**Issue by shorif2000** [Hargne/jest-html-reporter#49]
I run tests on phpunit and output xml dynamically into a different filename and would like to do same with jest. is there a way to do this?

is this correct way in perl

```
print "\n"; print "\nRunning Jest";
my $cmd = "export JEST_HTML_REPORTER_OUTPUT_PATH=$dir/docs/library/reports/jest$sprint_release.html && export JEST_HTML_REPORTER_PAGE_TITLE=\"Test_Report$sprint_release\"";
#print "\n$cmd\n";
system("$dir/utils/jest_env && $cmd && jest");
```

**Comment by Hargne** [comment]
Hi,

Unfortunately I have personally very little experience with Perl (so this might be a question that would get a better answer in a Perl-related forum) - but I suppose that if you are able to change the variable `JEST_HTML_REPORTER_OUTPUT_PATH ` on each run, it might be possible.
