### ISSUE TITLE
Question: Attach selenium test's screenshots in report

### ISSUE THREAD

**Issue by deepticake** [Hargne/jest-html-reporter#50]
How can we attach selenium test's screenshots in Jest HTML Report?

**Comment by Hargne** [comment]
Hi,

This is not a feature available right now, however I do like the idea of having the option to add custom content to the test report. 
One question though: are the screenshots tied to the individual test cases or is it a single file containing the summary?

**Comment by Hargne** [comment]
Hi,

Adding custom content to each Jest test case is unfortunately not as easy as it sounds. This has already been asked in #36 and the solution would be something similar for this one.

Until the Jest test context is exposed from within each test case, the best bet would be to alter the HTML report programatically and add the images after it has been rendered.
