### ISSUE TITLE
'includeFailureMsg': true & 'includeConsoleLog': true do not show the errors & logs in the HTML report

### ISSUE THREAD

**Issue by annasm15** [Hargne/jest-html-reporter#51]
I've added the following configuration in my jest.config.js file

![image](https://user-images.githubusercontent.com/43020293/45934494-4b33cc00-bfe2-11e8-8767-a471f4e2fe8e.png)

The report is generated - however, neither the console logs or the failure message are displayed:
![image](https://user-images.githubusercontent.com/43020293/45934596-6b17bf80-bfe3-11e8-84de-596f4a24c546.png)

In the documentation, one of your screenshots has the error displayed.

> ![image](https://user-images.githubusercontent.com/43020293/45934559-0eb4a000-bfe3-11e8-9d31-8fff4239b495.png)

How can this be done? What did I miss?

Thanks!

**Comment by Hargne** [comment]
First and foremost: thanks for such an awesome and detailed issue report! 🥇 Hats off!

It looks like it says "includeFai**ll**ureMsg" (with double Ls) in the configuration that you posted - it should be a single L in failure!

Get back to me if this solves the issue!

**Comment by annasm15** [comment]
Wooooops!!! 

Yes, it worked!
![image](https://user-images.githubusercontent.com/43020293/45982895-eccc2380-c09d-11e8-9cc7-3d4cbe881397.png)

How do I make the console logs appear in the HTML report though? <Not sure if there's a detailed step by step in the documentation.. can't find it..>

Thanks so much!

**Comment by Hargne** [comment]
To have console logs outputted into the report, you would use the `includeConsoleLog: true` setting.
Please note though that this will gather all logs from each test suite and output it below each suite (not below each test).

Also note that only console logs made in the actual tests, not the tested code, will be printed. I have had questions regarding how to trigger console logs from the tested code previously, but this is unfortunately not possible with the current state of Jest.

**Comment by annasm15** [comment]
Can you give an html report example of a simple jest test that has console logs in it and with includeConsoleLog: true ?

'Cause when I set includeConsoleLog to true, nothing changes in the report. I don't see any console logs..

Thanks again so much!

**Comment by Hargne** [comment]
Hi!
I apologize for the extremely slow response!
This might be related to #61 where having `verbose: true` in the jest config seems to be causing the console.logs to disappear from the Jest output.

I will close this issue and refer to #61 for continued discussion.
However, if you feel that this is a problem regardless of that issue, feel free to open this again
