### ISSUE TITLE
Change default path of jesthtmlreporter.config.json?

### ISSUE THREAD

**Issue by normancarcamo** [Hargne/jest-html-reporter#53]
Hi, I would like to change the path of this file, by default it has to be defined in the root, but in my case, I have a directory dedicated only for test configurations to help others working in the same project know where the configuration files for tests are placed, I know that I can inject the options directly into the jest.config.js, but I'm looking the option to keep the files decoupled.

Thanks.

**Comment by Hargne** [comment]
Hi,

Unfortunately since you'd need to define the location of the jesthtmlreporter.config file through the command line (which is occupied by Jest itself via `--config`), your best bet would actually be to use the Jest config to configure this plugin from elsewhere than the root folder.

**Comment by normancarcamo** [comment]
@Harne many thanks for the answer, actually that’s how I ended up doing so.
I would really like to have a bit more of space and time to propose a PR for this :)
