### ISSUE TITLE
Feature Request: Option to exclude generating full html markup

### ISSUE THREAD

**Issue by brewster1134** [Hargne/jest-html-reporter#54]
I am injecting the test results into an existing page, so am looking to generate only the test results without the html, meta, style tags, etc. It doesn't cause an actual issue, and i can just override the styles i want to change, but could this be a useful as an option for other users or use cases?

**Comment by Hargne** [comment]
Hi,
Since this reporter plugin is specifically for reporting the results as HTML, I would suggest using existing reporters that do just what you need!
Example: [jest-json-reporter](https://github.com/Vall3y/jest-json-reporter)

**Comment by brewster1134** [comment]
well i'm still looking for the test results as HTML, just not as a fully-fledged HTML page. just an html snippet with the table of results, suite info, etc.

**Comment by brewster1134** [comment]
not necessarily customize the HTML... the design of the test results is great. i just need everything inside the `<body>` tag, and nothing else. _(which btw... i noticed as i was inspecting the source HTML, that there isn't an actual `<body>` tag. the browser seems to know to wrap the content in one, but its not explicitly defined)_

but instead of...
```html
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test report</title>
    <style type="text/css">
      html, body {
        font-family: Arial, Helvetica, sans-serif;
       ...
     }    
   </style>
  </head>
  <header>
    <h1 id="title">Test report</h1>
  </header>
  <div id="metadata-container">
    <div id="timestamp">Start: 2018-12-11 14:37:54</div>
    <div id="summary">
      1 tests --
      1 passed /
      0 failed /
      0 pending
    </div>
  </div>
  <div class="suite-info">
    <div class="suite-path">/.tmp/foo_test.js</div>
    <div class="suite-time">0.371s</div>
  </div>
  <table class="suite-table" cellspacing="0" cellpadding="0">
    <tr class="passed">
      <td class="suite">foo</td>
      <td class="test">
        should have the class foo
        <div class="failureMessages"/>
      </td>
      <td class="result">passed in 0.004s</td>
    </tr>
  </table>
</html>
```

have an option to just render...
```html
<header>
  <h1 id="title">Test report</h1>
</header>
<div id="metadata-container">
  <div id="timestamp">Start: 2018-12-11 14:37:54</div>
  <div id="summary">
    1 tests --
    1 passed /
    0 failed /
    0 pending
  </div>
</div>
<div class="suite-info">
  <div class="suite-path">/.tmp/foo_test.js</div>
  <div class="suite-time">0.371s</div>
</div>
<table class="suite-table" cellspacing="0" cellpadding="0">
  <tr class="passed">
    <td class="suite">foo</td>
    <td class="test">
      should have the class foo
      <div class="failureMessages"/>
    </td>
    <td class="result">passed in 0.004s</td>
  </tr>
</table>
```

i also noticed as i was inspecting the source HTML, that there is no `<body>` tag. the browser seems to know to wrap the content in one, but its not explicitly rendered...

**Comment by Hargne** [comment]
Hi,

Adding the feature of customizing the HTML boilerplate would certainly make this a useful feature for more people than those who want the particular solution you're asking for.

Thanks for reporting about the omitted body tag. It is not required, but I will make sure to add it in in the next release.
