### ISSUE TITLE
sort order not correct for test suite with a lot of tests

### ISSUE THREAD

**Issue by SjoerdV** [Hargne/jest-html-reporter#55]
While having this order in my test suite:
![image](https://user-images.githubusercontent.com/13275320/50117668-eb019e80-024d-11e9-9a3e-93143a775a83.png)
the jest-html-reporter returns the wrong sort order for the individual tests within the suite:
![image](https://user-images.githubusercontent.com/13275320/50117542-94946000-024d-11e9-9850-cab9d93fff13.png)
This only seem to happen with larger test suites.
_note: I only numbered them for this issue ofcourse_

**Comment by yuanlinZhao** [comment]
![image](https://user-images.githubusercontent.com/36977336/76938958-80e51700-6932-11ea-92cf-643daa14a710.png)
excuse, why my report does not have test suite ? just tests  
![image](https://user-images.githubusercontent.com/36977336/76939141-d1f50b00-6932-11ea-8c87-5b72f9ce6a3e.png)

**Comment by Hargne** [comment]
@yuanlinZhao If you mean that there is no headline for the amount of test suites, it is because there has never been one there. If you are need for it, kindly post a separate issue stating what you need.

**Comment by Hargne** [comment]
Regarding the original issue:
I has been a while since I had a look at this, but I think that I have found the issue why this is happening: the tests are only sorted by `testFilePath` then `ancestorTitles`, not by the test title.

I will include a fix for this in the upcoming release of 3.0.0

**Comment by Hargne** [comment]
@SjoerdV If this still is relevant, you can test this feature in the new version by installing the beta version of 3.0.0:

`$ yarn add --dev jest-html-reporter@3.0.0-beta.2`

**Comment by Hargne** [comment]
I am closing this due to [v3.0.0](https://github.com/Hargne/jest-html-reporter/releases/tag/3.0.0)
Feel free to open if you still consider this an issue
