### ISSUE TITLE
Feature Request: Only print failure test case

### ISSUE THREAD

**Issue by mazipan** [Hargne/jest-html-reporter#60]

**Comment by Hargne** [comment]
Interesting feature that should be pretty simple to implement.

**Comment by oBlissing** [comment]
I am still getting a file printed, even if it's empty. Am I misunderstanding this feature?

I am ignoring `"passed, pending"`, so it only shows errors.

What I expected:
* I should only get errors printed (this works).
* When nothing to show, no report should be printed.

**Comment by Hargne** [comment]
There is currently no option to disable report rendering if there is no content output from the test suites. That would be a new feature request (unrelated to this feature)!

**Comment by oBlissing** [comment]
Ok, thanks for the clarification!

For anyone else looking for a quick solution:
Check the exit code or do a try/catch on the test call, and then you can act on the fail.

Example from my fabric script
````
                try:
                    local('yarn test:unit')
                except:
                    local('mv testreport.html dist')
````
