### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mkschaller** [Hargne/jest-html-reporter#66]
I did a lot of searching and this was the best reporter by far- thanks! I did, however, find a typo. I uploaded a screenshot of a report showing it. Passed is missing the 'e'. I didn't know where else to mention, so I figured this was the best place.

![typo](https://user-images.githubusercontent.com/22327993/55586214-0d7cd200-56ee-11e9-82f0-93c9abc063aa.png)

**Comment by Hargne** [comment]
Hi, and thanks!
The screenshot looks like a custom template or possibly even another plugin. There is no "all passed" string within either Jest nor this plugin :)

**Comment by mkschaller** [comment]
Duh, my bad. I posted in the wrong plugin. I've played with multiple and they have (almost) identical names.

**Comment by Hargne** [comment]
No worries!
