### ISSUE TITLE
Validate config via JSON Schema

### ISSUE THREAD

**Issue by nickshevr** [Hargne/jest-html-reporter#67]
Hi, I used `statusIgnoreFilter` option:

```
  "statusIgnoreFilter": ["passed"],
```

All of my tests are `passed`, so I got no html output.  Don't think it's good behaviour, cause empty output might be result of error at the same time.

Think is should be simple html with `No suites after statusIgnore` message into `body`.

**Comment by nickshevr** [comment]
I had wrong JSON btw, so I renamed issue. I can implement this validation.

**Comment by Hargne** [comment]
As was commented in the above PR:

> Hi,
> I am sorry for being extremely late to respond.
> 
> I like the idea of validating the config 👍 This will (somewhat) be handled in the new version 3.0.0 where the module has been ported over to Typescript and where I have added a similar approach as you do here.
> 
> With that said, this PR is now (because of me) unfortunately out of sync, although with the idea still lingering on into the new version!
> 
> Thanks buddy!
