### ISSUE TITLE
Emoji characters not supported 😔

### ISSUE THREAD

**Issue by RolfKoenders** [Hargne/jest-html-reporter#75]
Hello there!

First of all thanks for this reporter since it perfectly fit our needs. The only downside i just ran into is that when a test case name has an Emoji in the title it throws an error.
```js
it("Sending an Emoji 😃", function (done) {
```

The console output:
```bash
 PASS  test/integration/Integration.test.js
  POST /myEndpoint
    ✓ Sending an Emoji 😃 (425ms)
...
Ran all test suites.
jest-html-reporter >> Error: Invalid character (�) in string: Sending an Emoji 😃 at index 17
```

**Workaround:** For now i removed the Emoji from the 'it' 
**Version:** 2.5.0

**Comment by Hargne** [comment]
This should be fixed in [v2.6.0](https://github.com/Hargne/jest-html-reporter/releases/tag/2.6.0)
