### ISSUE TITLE
help - how to add "console.log" in the html report?

### ISSUE THREAD

**Issue by andreabisello** [Hargne/jest-html-reporter#77]
hi
i would like to add others information in the html report.
for example here
![image](https://user-images.githubusercontent.com/2149815/68196257-a04d5a00-ffb8-11e9-9d72-5ef6ad6986ff.png)
i would like to add some comments,
for example
console.log ("user making login is X with password Y)"
for obtaining something like this
![image](https://user-images.githubusercontent.com/2149815/68196381-d2f75280-ffb8-11e9-9e62-4b0b5607487b.png)
i'm a bit confused : 
who should add this information in the report file? jest ? the report parser? node?
thanks for helping.

**Comment by Hargne** [comment]
Hi,
It has been a bit tricky to reliably get the console.logs from Jest as of lately. Luckily I was able to catch the logs manually and insert them into the report. Please test the latest version: https://github.com/Hargne/jest-html-reporter/releases/tag/2.7.0

It is now possible to gather all console.logs for the test suites below each suite by adding `includeConsoleLog` to the jest-html-reporter options in the jest config.

It is however (as of now) not possible to get the console.logs to output per test - they will be collected per test suite.

**Comment by andreabisello** [comment]
@Hargne thanks.

i make this test file

```
describe('temptative', () => {

    test("try foo", async () => {
        console.log("foo foo foo foo foo")
        expect(2).toBe(2)
    })

    test("try bar", async () => {
        console.log("bar bar bar bar bar bar")
        expect(2).toBe(3)
    })

})
```

i updated the library from 2.6.2
![image](https://user-images.githubusercontent.com/2149815/68211440-dea64180-ffd7-11e9-81c0-85e6d03a35b4.png)
to 2.7.0
![image](https://user-images.githubusercontent.com/2149815/68211465-e8c84000-ffd7-11e9-9cc4-8b9dc0cbf858.png)
this is my jest config
```
module.exports = {
    preset: "jest-puppeteer",
    setupFilesAfterEnv: [  // NOT setupFiles
        "./custom-configuration.js",
        "jest-allure/dist/setup"
    ],
    "reporters": [
        "default",
        ["./node_modules/jest-html-reporter", {
            "pageTitle": "Test Report",
            "includeFailureMsg": true,
            "includeConsoleLog": true
        }],
        ["jest-junit", { outputName: "junitreport.xml" }]
    ]
};
```
and i run jest with this command

![image](https://user-images.githubusercontent.com/2149815/68211589-29c05480-ffd8-11e9-868b-97c05240aeab.png)

but there is no console.log in the test-report.html file

![image](https://user-images.githubusercontent.com/2149815/68211648-3e9ce800-ffd8-11e9-8ec2-e17627fb23a4.png)

**Comment by Hargne** [comment]
Interesting. Thanks for the detailed report! 
I see that you're using async methods (without await, which should be fine) - can you please test the same thing without `async`, so that we can rule that out?

**Comment by andreabisello** [comment]
@Hargne nothing changed.

```
describe('temptative', () => {

    test("try foo", () => {
        console.log("foo foo foo foo foo")
        expect(2).toBe(2)
    })

    test("try bar", () => {
        console.log("bar bar bar bar bar bar")
        expect(2).toBe(3)
    })

})
```

**Comment by Hargne** [comment]
Alright!
I recreated your scenario on my machine and I managed to get it working by specifying `--verbose=false` when running jest. Please test if this works for you as well.

I will make sure to add this to the documentation.

**Comment by andreabisello** [comment]
@Hargne 
as you say.
thanks
