### ISSUE TITLE
includeFailureMsg not work

### ISSUE THREAD

**Issue by duckscofield** [Hargne/jest-html-reporter#83]
I have try all closed issues. I could not see fail test case on html, it only show **pass** cases.

```
...
testResultsProcessor: ./node_modules/jest-html-reporter                                                                               
},                                                                                                   
jest-html-reporter: {                                                                                
pageTitle¦: Test Suite,                                                   
outputPath: reports/run-jest-test-report.html,                                                 
includeFailureMsg: true,                                                                         
},
...
```

In my terminal console, I has these information:
```
Test Suites: 4 failed, 1 passed, 5 total
Tests:       3 passed, 3 total
Snapshots:   3 passed, 3 total
Time:        6.788s
```

**Comment by Hargne** [comment]
Hi,
First of all, sorry for being late to respond!

It looks like it is the suite that is failing - not any of the tests that are included in the report.
FYI: There is a [new version](https://github.com/Hargne/jest-html-reporter/releases/tag/v3.0.0-beta.0) in the making in which the numbers of results for the suites have been added to the top of the report.

**Comment by Hargne** [comment]
I am closing this due to [v3.0.0](https://github.com/Hargne/jest-html-reporter/releases/tag/3.0.0)
Feel free to open if you still consider this an issue
