### ISSUE TITLE
jest-html-reporter >> TypeError: callback is not a function

### ISSUE THREAD

**Issue by Sathyanarayanan07** [Hargne/jest-html-reporter#85]
The below line of code using jest.spyOn throws a typeError as given in the title.I am unable to suppress the error and html reporter is not generated

```
it('', () => {

jest.spyOn(fs, 'readFile')
.mockImplementation((_, callback) => callback(null, Buffer.from('Test Read File')));

});
```

Anyway can i suppress this and generate the reported ?

**Comment by Hargne** [comment]
Hi,

It seems like the `readFile` spy that you are setting up is spilling over to jest-html-reporter somehow.
I can think of two solutions:
1. Attempt checking the callback before calling it, for example: 
`(_, callback) => (typeof callback === 'function') && callback(null, Buffer.from('Test Read File'))`
2. Try using the new version **v3.0.0-beta.1** currently in testing by installing: 
`npm install jest-html-reporter@3.0.0-beta.1 --save-dev`

**Comment by Hargne** [comment]
I will close this due to inactivity, feel free to open it again if you still feel that this is an issue.
