### ISSUE TITLE
Add support for new Jest version 25.1.0.

### ISSUE THREAD

**Issue by skrtheboss** [Hargne/jest-html-reporter#86]
Add support for new Jest version 25.1.0.

`warning " > jest-html-reporter@2.8.0" has incorrect peer dependency "jest@19.x - 24.x".`

**Comment by Hargne** [comment]
I will look at this when I can :)
Also: feel free to post PRs if you believe that you are able to solve this!

**Comment by Hargne** [comment]
Fixed in [v2.8.2](https://github.com/Hargne/jest-html-reporter/releases/tag/2.8.2)
