### ISSUE TITLE
Console Log are always sorted by path, and not by time when they were originated.

### ISSUE THREAD

**Issue by alexeytemnikov** [Hargne/jest-html-reporter#87]
In commit b0cbd1359a434a561667f54b2a9d4cdaf1724941 (version 2.7.0) new feaature was added to sort the logs based on file path - 

#78 
`filteredConsoleLogs.logs.sort((a, b) => {
 						if (a.origin < b.origin) {
 							return -1;
 						}
 						if (a.origin > b.origin) {
 							return 1;
 						}
 						return 0;
 					});`

While I see this functionality might be useful, for some use cases it is needed to maintain logs in the order they were received ( which is currently matches to the order they were created), If logs are originated in some helper files (not from the JS file with test / describe block), this logic will sort out the logs by path and will break the timeline, which is very useful for to have in the report. It also considers line number, and sorting is done based on the string comparing, not line number comparing.

This behaviour breaks one of the very useful use case for the report.

I suggest not to sort  the logs by default (perhaps maybe to have ability to control it with flag or make it pluggable).

**Comment by Hargne** [comment]
Hi,

Thanks for the input.
I will have a look at this asap

**Comment by Hargne** [comment]
@alexeytemnikov Please have a look at #91 and see if this fixes your issue

**Comment by Hargne** [comment]
This was fixed in [v2.8.2](https://github.com/Hargne/jest-html-reporter/releases/tag/2.8.2)
