### ISSUE TITLE
Ability to add meta-data or a screenshot per test?

### ISSUE THREAD

**Issue by tomardern** [Hargne/jest-html-reporter#88]
Hi,

I was wondering if there is a way to add any meta-data or an image screenshot per test?

Thanks,

**Comment by Hargne** [comment]
Hi,
The plugin processes the test results given from Jest after a test run, which at the moment does not include any image sources unfortunately.

What sort of meta-data are you interested in adding to the tests?

**Comment by tomardern** [comment]
We use the jest-html-reporter as a reporter for our E2E test (Jest+Puppeteer).

The main thing is video/screenshot for each of our tests, or things like the user the E2E tests ran, the machine type/if it's mobile/desktop etc.

**Comment by Hargne** [comment]
I would suggest using a tool specifically created for that purpose, like [jest-screenshot](https://github.com/Prior99/jest-screenshot) for example

**Comment by tomardern** [comment]
hi Hargne - it's more the case of showing the video that our E2E produced, and the screenshots it produced.

**Comment by Hargne** [comment]
So in short you want to inject data into the HTML after the testing is done?

For modifying of files after they have been generated, I would again refer to using another tool for that specific use-case. 

If you want to be able to locate a specific test within the file and pair it together with something from the outside, it would require a unique identifier.
As for [what you receive from Jest](https://jestjs.io/docs/en/configuration#testresultsprocessor-string) in terms of identifiers per test case, we are pretty limited - the only thing that is somewhere close (but not entirely) to being an identifier is the file path of the test-file (which in turn would not make it possible to separate each test case within that file other by the test name).

**Comment by tomardern** [comment]
Yes - that is correct. Sadly Jest is limited for this :(

I've figured out a bit of a "hack" to do this. 

During the test run, I `md5(file path + test index)` to create a unique identifier, then calculate this again when injecting the script in via your plugin.

The Javascript to amend the reporter:

```js

/*
Add the view-video button
*/
Array.from(document.querySelectorAll('.suite-table')).forEach(suiteElem => {
  var testSuiteFile = suiteElem.previousSibling.querySelector('.suite-path').innerText.trim();
  Array.from(suiteElem.querySelectorAll('tr')).forEach((testElem, index) => {
    testElem.insertAdjacentHTML(
      'beforeend',
      `<td><a class="view-video" test-file="${md5(testSuiteFile)}-${index}"> View Video</a></td>`
    );
  });
});

/*
On click, display the video 
*/
Array.from(document.querySelectorAll('.view-video')).forEach(elem => {
  elem.addEventListener('click', function() {
    const testElem = elem.closest('tr').querySelector('.test');
    const videoElem = testElem.querySelector('.video');
    if (videoElem) {
      videoElem.parentNode.removeChild(videoElem);
    } else {
      const testFile = elem.getAttribute('test-file');
      const videoUrl = `./${testFile}.mp4`;
      testElem.insertAdjacentHTML(
        'beforeend',
        `<video class="video" controls autoplay src="${videoUrl}"/>`
      );
    }
  });
});
```

But does show this:

![image](https://user-images.githubusercontent.com/1135454/77158578-7e520100-6a9b-11ea-8712-79cb226942b0.png)

It'll be nice if there is some built in way of storing meta-data when the test runs, then picking it up in your reporter.

**Comment by Hargne** [comment]
The ability to add custom items to the tests have been [https://github.com/Hargne/jest-html-reporter/issues/36#issuecomment-371782663](requested before).
I haven't done any investigations as of lately regarding the matter above, but feel free to do so and report if you find any news!

**Comment by tomardern** [comment]
@Hargne will do :)
