### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by pascalduez** [Hargne/jest-html-reporter#9]
Hi,

the latest releases are not working anymore on node 4.
I guess there's some unsupported ES6 features being used.

But there's no Changelog, no notice in Readme, nor an `engine` key in package.json.

**Comment by Hargne** [comment]
Thank you for the message!
I will have a look ASAP.

**Comment by pascalduez** [comment]
I would bet on the destructured default params.

**Comment by Hargne** [comment]
Which exact version of Node are you using?

**Comment by pascalduez** [comment]
> Which exact version of Node are you using?

`4.8.3`

**Comment by Hargne** [comment]
Thanks for the information.
I have made some changes, tested it against Node 4.8.3 and it looks like it is working fine.
Would you mind checking out the branch mentioned above and verify against your environment?

**Comment by pascalduez** [comment]
@Hargne All tests passes on the `#9-Node-4-support` branch. Node `4.8.3`.

Thanks!

**Comment by Hargne** [comment]
Great I will make sure to merge and create a new release!
