### ISSUE TITLE
includeConsoleLog not working?

### ISSUE THREAD

**Issue by andreabisello** [Hargne/jest-html-reporter#93]
this is  my jest.config.js

```
module.exports = {
    preset: "jest-puppeteer",
    setupFilesAfterEnv: [  // NOT setupFiles
        "./configurazioni/custom-configuration.js",
        "./configurazioni/shared-require.js",
        "jest-allure/dist/setup"
    ],
    "reporters": [
        "default",
        ["./node_modules/jest-html-reporter", {
            "pageTitle": "Test Report",
            "includeFailureMsg": true,
            "includeConsoleLog": true,
            "outputPath":"reports/"+new Date().getDate() + "-" +
                (new Date().getMonth() + 1) + "-"
                + new Date().getFullYear()+ "-"
                + new Date().getHours().toString() + "-"
                + (new Date().getMinutes() + 1 ).toString() + "-"
                + (new Date().getSeconds() + 1 ).toString()
                +"-run.html"
        }],
        ["jest-junit", { outputName: "reports/junitreport.xml" }]
    ],
    moduleNameMapper: { //serve per poter usare $lib
        '^\\$lib\/(.*)': `<rootDir>/lib/$1`,
    },
};
```

when i run jest ,

file as 23-3-2020-15-33-32-run.html will be created, and this because "outputPath" will be considered.

![image](https://user-images.githubusercontent.com/2149815/77329270-0e06e200-6d1e-11ea-89be-3db61f05cc21.png)

as you can see, there are a lot of console.log in my execution

![image](https://user-images.githubusercontent.com/2149815/77329307-1ced9480-6d1e-11ea-8059-5e55756e429f.png)

but in the reporter there are any console.log

![image](https://user-images.githubusercontent.com/2149815/77329394-3c84bd00-6d1e-11ea-8f36-1bfc77bb78f3.png)

so is "includeConsoleLog" working?

there are my versions

- jest 24.9
- jest-html-reporter 2.8.2
- node 12.13.0

thanks.

**Comment by Hargne** [comment]
Hi,

Thanks for the detailed report.
I remember we had a similar discussion in a [previous issue](https://github.com/Hargne/jest-html-reporter/issues/77#issuecomment-549844796), where it was concluded that the Jest needed to be run with `--verbose=false`

Can you first check if this still is the case or not before I continue investigating?

**Comment by andreabisello** [comment]
@Hargne  you are right *SORRY*.
the fact the verbosity and the console.log cannot co-exists is a wanted behaviour?

**Comment by Hargne** [comment]
It is how Jest works in the way that its default behaviour is to suppress individual logs and warnings during tests. [You can read more about it here](https://jestjs.io/docs/en/configuration#verbose-boolean).

[I added this to the Wiki](https://github.com/Hargne/jest-html-reporter/wiki/configuration#includeconsolelog-boolean) after our last conversation, but I will make sure to add this information to the README as well in the coming release.

**Comment by andreabisello** [comment]
@Hargne  very thanks.
