### ISSUE TITLE
`ouputPath` does not use `<rootDir>` token anymore - 3.x

### ISSUE THREAD

**Issue by pascalduez** [Hargne/jest-html-reporter#98]
Hi,

in version 2.x the Jest `<rootDir>` token was properly used and converted when used in config.
Starting from 3.x is not the case anymore and I don't see anything related in the changelog, regression?

```js
{
  pageTitle: 'Hello',
  outputPath: '<rootDir>/reports/index.html',
},
```

**Comment by Hargne** [comment]
Hi,
Thanks for pointing this out - as you say this is missing, and was unintentionally left out of 3.0.0
I will add it right back!

**Comment by Hargne** [comment]
The PR above aims to fix this issue 👍
